name: mango_cms
version: 1.0.3
description: Wrapper for CMS API
repository: https://github.com/louisevanderlith/cms
homepage: https://github.com/louisevanderlith/cms
environment:
  sdk: '>=2.0.0 < 3.0.0'
dependencies:
  mango_ui: '^1.0.3'